title: My Awesome Website
description: > # this means to ignore newlines until "baseurl:"
  This is a website created using GitHub Pages and Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://triyasmkom.github.io" # the base hostname & protocol for your site

markdown: kramdown
theme: minima
